FROM python:3.11-slim

WORKDIR /app

# Bağımlılıkları yükle
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Bot kodunu kopyala
COPY main.py .

# Botu çalıştır
CMD ["python", "main.py"]
